=== politecnicojic2022-santiago/Taller1-Punto6/listacursos.dtd
<!ELEMENT listacursos (curso+)>
<!ELEMENT curso (alumno+)>
<!ELEMENT alumno (DNI, nombre, apellido, segundo-apellido?,asignatura+)>
<!ELEMENT asignatura (nombre, profesor)>
<!ATTLIST asignatura codigo ID #REQUIRED>
<!ELEMENT profesor (NRP, nombre, apellido, segundo-apellido?)>
<!ELEMENT NRP (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT segundo-apellido (#PCDATA)>

=== politecnicojic2022-santiago/Taller1-Punto6/listacursos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE listacursos SYSTEM "listacursos.dtd">
<listacursos>
    <curso>
        <alumno>
            <DNI>1000893886</DNI>
            <nombre>Santiago</nombre>
            <apellido>Cano</apellido>
            <segundo-apellido>Ospina</segundo-apellido>
            <asignatura codigo="A13221">
                <nombre>Matamaticas</nombre>
                <profesor>
                    <NRP>21142121310</NRP>
                    <nombre>Carlos</nombre>
                    <apellido>Pérez</apellido>
                </profesor>
            </asignatura>
            <asignatura codigo="B57666">
                <nombre>Aritmetica</nombre>
                <profesor>
                    <NRP>21142121310</NRP>
                    <nombre>Carlos</nombre>
                    <apellido>Pérez</apellido>
                </profesor>
            </asignatura>
        </alumno>
    </curso>
</listacursos>
